---
# tasks file for httpd

- name: install httpd
  yum:
    name: httpd
    state: present
- name: copy index.html
  template:
    src: index.html
    dest: /var/www/html/index.html
  notify:
  - start httpd
