- hosts: 172.31.12.47
  become: yes
  tasks:
  - name: uninstall jenkins
    yum:
      name: jenkins
      state: absent
  - name: Remove Jenkins Repo
    file:
      path: /etc/yum.repos.d/jenkins.repo
      state: absent

