
- hosts: 172.31.9.154
  become: yes
  tasks:
  - name: Installation of packages
    ignore_errors: yes  
    yum:
      name: "{{item}}"
      state: present
    with_items:
    - vim
    - unzip
    - wget
    - git
    - tar

